# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='店铺信息')),
                ('cover', models.ImageField(default='static/images/default.jpg', upload_to='static/images/shop', verbose_name='店铺封面')),
                ('intro', models.TextField()),
                ('opener_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, verbose_name='店铺状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='店铺所属用户')),
            ],
        ),
    ]
