# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='店铺名称')),
                ('cover', models.ImageField(default='store/static/cover/default.jpg', upload_to='store/static/cover/', verbose_name='店铺封面')),
                ('intro', models.TextField(verbose_name='店铺描述')),
                ('state', models.IntegerField(default=0, verbose_name='店铺状态')),
                ('open_time', models.DateField(auto_now_add=True, verbose_name='开店时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='店铺所有者')),
            ],
        ),
    ]
